AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TodoSrcBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      AccessControl: AuthenticatedRead
      BucketName: "todo-src-bucket"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
Outputs:
  TodoSrcBucketName:
    Value: !Ref TodoSrcBucket
